### ISSUE TITLE
question: root

### ISSUE THREAD

**Issue by Kaiko77456** [kitadai31/revanced-manager-android5-7#10]
### Description

Root need install microG?? 

Android version
7.0

Manager version
1.9.5-API23

Target app name
YouTube

Target app version.
17.34.36

Installation type
root

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have written the title and contents in English.

**Comment by KobeW50** [comment]
Nope (not sure why this issue is still open)

**Comment by kitadai31** [comment]
I made the guide for root installation 2 month ago, but I forgot to tell it in this issue
https://github.com/kitadai31/revanced-patches-android6-7/wiki/How-to-build-(Rooted)
