### ISSUE TITLE
bug: no patches found for YouTube 17.34.36

### ISSUE THREAD

**Issue by nicoleahmed** [kitadai31/revanced-manager-android5-7#11]
### Bug description

Using this revanced manager on moto g4 and on pixel 6 pro. No patches possible with YouTube 17.34.36 and kitadai patches.

Kitadai patches also not applying through new revanced manager. 

![Screenshot_20231210-125520](https://github.com/kitadai31/revanced-manager-android5-7/assets/38244338/4a9d417c-5147-467d-a059-4df19e9a917f)
![IMG-20231210-WA0022](https://github.com/kitadai31/revanced-manager-android5-7/assets/38244338/fd64f5e1-d7b3-4916-8ec3-7b073550c287)
![Screenshot_20231210-125526](https://github.com/kitadai31/revanced-manager-android5-7/assets/38244338/b383a6fa-236b-4e0c-84c2-265b692fcff2)
![IMG-20231210-WA0019](https://github.com/kitadai31/revanced-manager-android5-7/assets/38244338/24730b8b-4f20-43ef-bf31-de06d5b40cb4)
![IMG-20231210-WA0020](https://github.com/kitadai31/revanced-manager-android5-7/assets/38244338/173c7cb3-9985-41a2-a825-f48e66078cc8)
![IMG-20231210-WA0021](https://github.com/kitadai31/revanced-manager-android5-7/assets/38244338/35e2f5f6-63f9-498f-ac9d-69c4d941734c)

### Version of ReVanced Manager and version & name of application you tried to patch

As above

### Installation type

None

### Device logs

```shell
beginning of system

12-10 12:49:37.067 17331 17331 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/ file_picker/ com.google.android.youtube_17.34.36-1531307456_minAPI23(arm64- v8a, armeabi-v7a,x86, x86_64)(nodpi)_apkmirror.com.apk Binary XML file line

#41

12-10 12:49:45.635 17331 17331 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/ file_picker/ com.google.android.youtube_17.34.36-1531307456_minAPI23(arm64- v8a, armeabi-v7a,x86, x86_64)(nodpi).apkmirror.com.apk Binary XML file line

#41

12-10 12:50:21.766 17331 17331 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/ file_picker/

com.google.android.youtube_17.34.36-1531307456_minAPI23(arm64- v8a, armeabi-v7a,x86, x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41

12-10 12:54:00.452 17331 17331 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/app.revanced.manager.flutter/cache/ file_picker/ com.google.android.youtube_17.34.36-1531307456_minAPI23(arm64- v8a, armeabi-v7a,x86, x86_64)(nodpi)_apkmirror.com.apk Binary XML file line #41
```

### Patcher logs

```shell
None
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by kitadai31** [comment]
maybe GitHub API rate limit
Wait an hour

Access to this page to check if you are rate limited
https://api.github.com/

**Comment by kitadai31** [comment]
Support GitHub late limit in v1.17.1
