### ISSUE TITLE
bug: yt video stopping in 9 sec

### ISSUE THREAD

**Issue by Rohit0072** [kitadai31/revanced-manager-android5-7#17]
### Bug description

Whenever I try to open video it stuck on 9 sec and then start after a minute or two, and some time I have to close and open the app 4-5 time then I can play the video the youtube version is 17.34.36 issue in android 7.1.1 

### Version of ReVanced Manager and version & name of application you tried to patch

Version: 1.17.6
Model: CPH1729
Android Version: 7.1.1
Supported Archs: arm64-v8a, armeabi-v7a, armeabi
YouTube 17.34.36 

### Installation type

Non-root

### Device logs

```shell
--------- beginning of main
09-26 18:37:36.404 20435 20435 W RenderThread: type=1400 audit(0.0:154717): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
09-26 18:38:26.958 20435 20435 W RenderThread: type=1400 audit(0.0:155949): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
09-26 18:38:54.598 20435 20435 W RenderThread: type=1400 audit(0.0:158348): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by Rohit0072** [comment]
I am facing this issue for a week now please solve this😭

**Comment by kitadai31** [comment]
It's not a Manager's problem, and read the release page for solution.
https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.10

**Comment by Rohit0072** [comment]
Thank you for the solution 😊
