### ISSUE TITLE
bug: Unable to connect to server 

### ISSUE THREAD

**Issue by Rohit0072** [kitadai31/revanced-manager-android5-7#18]
### Bug description

When I am playing videos on yt it shows me unable to connect to server playback I'd (), please fix this for me

### Version of ReVanced Manager and version & name of application you tried to patch

Revenced manager 1.17. 6
Revenced youtube 17.34.36 

### Installation type

None

### Device logs

```shell
--------- beginning of main
09-26 18:37:36.404 20435 20435 W RenderThread: type=1400 audit(0.0:154717): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
09-26 18:38:26.958 20435 20435 W RenderThread: type=1400 audit(0.0:155949): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
09-26 18:38:54.598 20435 20435 W RenderThread: type=1400 audit(0.0:158348): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by kitadai31** [comment]
Fixed in the latest patches
https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v2.160.12
